import type { Guide } from '@/types/guides';

export const guidesNe: Guide[] = [

  // ── 1. WORD COUNTER ────────────────────────────────────────────
  {
    slug: 'word-counter-guide',
    toolSlug: 'word-counter',
    category: 'text-tools',
    title: 'शब्द गणना गाइड: अनलाइन Word Counter (2026)',
    subtitle: 'SEE/NEB परीक्षा, विश्वविद्यालय र सोशल मिडियाका लागि शब्द गणना गर्ने सम्पूर्ण जानकारी।',
    metaTitle: 'शब्द गणना - नेपाली अनलाइन Word Counter टूल',
    metaDescription: 'लेख, निबन्ध वा पाठको शब्द तुरुन्त गणना गर्नुहोस्। SEE/NEB परीक्षा, TU thesis र सोशल मिडियाका लागि निःशुल्क शब्द गणना उपकरण। नेपाली भाषा support।',
    targetKeyword: 'शब्द गणना',
    secondaryKeywords: ['शब्द गणना गर्ने', 'नेपाली शब्द काउन्टर', 'SEE NEB निबन्ध शब्द', 'अनलाइन शब्द जाँच', 'अक्षर गणना', 'word count nepali', 'TU thesis word count', 'निबन्ध शब्द सीमा', 'character count nepali', 'Lok Sewa nibandha'],
    lastUpdated: '2026-03-12',
    readingTime: '७ मिनेट पढ्ने',
    tags: ['लेखन', 'निबन्ध', 'SEE', 'NEB'],
    intro: `<p><strong>शब्द गणना</strong> उपकरण प्रत्येक विद्यार्थी, लेखक र content creator को आवश्यकता हो। SEE परीक्षामा निबन्ध लेख्दा, Tribhuvan University को assignment तयार गर्दा, वा Lok Sewa को essay लेख्दा — सही <strong>word count</strong> जान्नु अत्यन्त महत्वपूर्ण छ।</p><p>हाम्रो निःशुल्क <strong>अनलाइन शब्द गणना</strong> टूलले नेपाली देवनागरी, अंग्रेजी र जुनसुकै भाषाको शब्द सेकेन्डमा गन्छ।</p>`,
    sections: [
      {
        id: 'shabd-ganana-kina',
        title: 'शब्द गणना किन महत्वपूर्ण छ?',
        content: `<ul><li><strong>SEE/NEB परीक्षामा:</strong> निबन्धको शब्द सीमा हुन्छ। बढी लेख्दा अंक काट्न सक्छ।</li><li><strong>विश्वविद्यालयमा:</strong> TU, KU को thesis र assignments मा कडा शब्द सीमा हुन्छ।</li><li><strong>Lok Sewa मा:</strong> निबन्ध परीक्षामा शब्द सीमा भित्र लेख्नु जरुरी छ।</li><li><strong>सोशल मिडियामा:</strong> Facebook, Instagram, Twitter का character limits अलग-अलग हुन्छन्।</li></ul>`,
      },
      {
        id: 'see-neb-nibandha-shabd',
        title: 'SEE/NEB परीक्षाका लागि निबन्ध शब्द सीमा',
        content: `<table><tr><th>परीक्षा / उद्देश्य</th><th>शब्द सीमा</th></tr><tr><td>SEE परीक्षा निबन्ध</td><td>200–250 शब्द</td></tr><tr><td>NEB Class 11/12</td><td>300–400 शब्द</td></tr><tr><td>TU Bachelor Assignment</td><td>1,000–2,000 शब्द</td></tr><tr><td>TU Master Thesis</td><td>15,000–25,000 शब्द</td></tr><tr><td>Lok Sewa निबन्ध</td><td>250–500 शब्द</td></tr><tr><td>Blog Post (SEO)</td><td>1,500–2,500 शब्द</td></tr></table>`,
      },
      {
        id: 'social-media-limit',
        title: 'Social Media Character Limits (2026)',
        content: `<table><tr><th>Platform</th><th>Post Limit</th><th>Bio Limit</th></tr><tr><td>Facebook</td><td>63,206 characters</td><td>101 characters</td></tr><tr><td>Instagram Caption</td><td>2,200 characters</td><td>150 characters</td></tr><tr><td>Twitter / X</td><td>280 characters</td><td>160 characters</td></tr><tr><td>TikTok</td><td>2,200 characters</td><td>80 characters</td></tr><tr><td>Viber Message</td><td>10,000 characters</td><td>—</td></tr></table>`,
      },
      {
        id: 'shabd-bata-pana',
        title: 'कति शब्द = कति पेज?',
        content: `<table><tr><th>शब्द</th><th>Single Space</th><th>Double Space</th></tr><tr><td>250</td><td>0.5 पेज</td><td>1 पेज</td></tr><tr><td>500</td><td>1 पेज</td><td>2 पेज</td></tr><tr><td>1,000</td><td>2 पेज</td><td>4 पेज</td></tr><tr><td>2,000</td><td>4 पेज</td><td>8 पेज</td></tr></table>`,
      },
    ],
    howToSteps: [
      { title: 'पाठ टाँस्नुहोस्', description: 'आफ्नो लेख वा निबन्ध copy गरेर box मा paste गर्नुहोस्।' },
      { title: 'गणना हेर्नुहोस्', description: 'शब्द, अक्षर, वाक्य र अनुच्छेद तुरुन्त देखिन्छ।' },
      { title: 'नेपाली पाठ', description: 'देवनागरी नेपाली र अंग्रेजी दुवैका शब्द सही गन्छ।' },
      { title: 'Character limit जाँच्नुहोस्', description: 'Social media post character limit भित्र छ कि छैन हेर्नुहोस्।' },
      { title: 'Real-time अपडेट', description: 'टाइप गर्दागर्दै count स्वतः अपडेट हुन्छ।' },
    ],
    faqs: [
      { question: 'नेपाली भाषाको शब्द गन्न सकिन्छ?', answer: 'हो, हाम्रो word counter नेपाली देवनागरी, अंग्रेजी र जुनसुकै भाषाका शब्द सही गन्छ।' },
      { question: 'SEE को निबन्धमा कति शब्द लेख्ने?', answer: 'SEE परीक्षामा 200-250 शब्दको निबन्ध लेख्नु उचित हुन्छ। NEB Class 11/12 मा 300-400 शब्द।' },
      { question: 'अक्षर र शब्दमा के फरक छ?', answer: 'शब्द भनेको अक्षरहरूको समूह हो। अक्षर (character) भनेको प्रत्येक letter, space र punctuation mark हो।' },
      { question: 'Lok Sewa को निबन्धमा कति शब्द?', answer: 'Lok Sewa को विभिन्न पदका लागि 250-500 शब्दको निबन्ध हुन सक्छ।' },
      { question: 'Instagram caption को limit कति छ?', answer: 'Instagram caption को limit 2,200 characters छ। तर "More" button अघि 125 characters मात्र देखिन्छ।' },
    ],
    relatedGuides: ['bmi-calculator-guide', 'percentage-calculator-guide'],
    toolCTA: { heading: 'अहिले निःशुल्क Word Counter प्रयोग गर्नुहोस्!', description: 'पाठ paste गर्नुहोस् र तुरुन्त शब्द, अक्षर, वाक्य गन्नुहोस्।', buttonText: 'शब्द गणना खोल्नुहोस् →' },
  },

  // ── 2. BMI CALCULATOR ──────────────────────────────────────────
  {
    slug: 'bmi-calculator-guide',
    toolSlug: 'bmi-calculator',
    category: 'calculators',
    title: 'BMI क्याल्कुलेटर गाइड: नेपाली वजन जाँच (2026)',
    subtitle: 'नेपाली मानिसहरूका लागि BMI गणना, आदर्श वजन र स्वस्थ जीवनशैली टिप्स।',
    metaTitle: 'बीएमआई क्याल्कुलेटर - आफ्नो वजन जाँच्नुहोस्',
    metaDescription: 'आफ्नो BMI गणना गर्नुहोस् र स्वास्थ्य अवस्था जान्नुहोस्। नेपाली मानिसहरूको आदर्श वजन chart, एसियाली BMI मानक र स्वास्थ्य सुझाव सहित। निःशुल्क।',
    targetKeyword: 'बीएमआई क्याल्कुलेटर',
    secondaryKeywords: ['BMI calculator nepali', 'नेपाली आदर्श वजन', 'स्वास्थ्य क्याल्कुलेटर', 'body mass index nepal', 'वजन र उचाई', 'मोटोपन जाँच', 'height weight nepal', 'ideal weight nepali woman', 'BMI formula nepali', 'nepali health calculator'],
    lastUpdated: '2026-03-12',
    readingTime: '८ मिनेट पढ्ने',
    tags: ['स्वास्थ्य', 'BMI', 'वजन', 'फिटनेस'],
    intro: `<p><strong>बीएमआई क्याल्कुलेटर</strong> ले तपाईंको वजन र उचाईको आधारमा बताउँछ कि तपाईं स्वस्थ वजनमा हुनुहुन्छ कि हुनुहुन्न। नेपालमा जीवनशैलीसँग सम्बन्धित रोगहरू (मधुमेह, उच्च रक्तचाप) बढ्दो छन् — आफ्नो <strong>BMI</strong> जान्नु महत्वपूर्ण छ।</p><p>एसियाली मानिसहरूका लागि WHO ले 23+ BMI लाई अधिक वजन मान्छ (पश्चिमी 25+ को सट्टा)।</p>`,
    sections: [
      {
        id: 'bmi-ke-ho',
        title: 'BMI के हो र सूत्र के हो?',
        content: `<blockquote><strong>BMI = वजन (kg) ÷ [उचाई (m)]²</strong></blockquote><p>उदाहरण: 65 kg, 1.65 m: BMI = 65 ÷ 2.7225 = <strong>23.9</strong></p>`,
      },
      {
        id: 'bmi-range-chart',
        title: 'BMI श्रेणी तालिका (एसिया/नेपाल मानक)',
        content: `<table><tr><th>BMI</th><th>श्रेणी</th><th>जोखिम</th></tr><tr><td>&lt;18.5</td><td>कम वजन</td><td>पोषणको कमी</td></tr><tr><td>18.5–22.9</td><td>सामान्य</td><td>न्यूनतम</td></tr><tr><td>23–24.9</td><td>अधिक वजन (एसिया)</td><td>मध्यम</td></tr><tr><td>25–29.9</td><td>मोटोपन Grade 1</td><td>उच्च</td></tr><tr><td>30+</td><td>मोटोपन Grade 2</td><td>गम्भीर</td></tr></table>`,
      },
      {
        id: 'nepali-ideal-weight',
        title: 'नेपाली मानिसहरूको आदर्श वजन',
        content: `<table><tr><th>उचाई</th><th>पुरुष (kg)</th><th>महिला (kg)</th></tr><tr><td>152 cm (5'0")</td><td>43–55</td><td>41–52</td></tr><tr><td>157 cm (5'2")</td><td>46–58</td><td>44–55</td></tr><tr><td>163 cm (5'4")</td><td>49–62</td><td>47–59</td></tr><tr><td>168 cm (5'6")</td><td>53–66</td><td>50–63</td></tr><tr><td>173 cm (5'8")</td><td>57–71</td><td>54–67</td></tr></table>`,
      },
      {
        id: 'swastha-bmi',
        title: 'स्वस्थ BMI कसरी प्राप्त गर्ने?',
        content: `<ul><li><strong>दाल-भातको सही मात्रा:</strong> कार्बोहाइड्रेट नियन्त्रण गर्नुहोस्, तरकारी र फलफूल बढाउनुहोस्।</li><li><strong>दैनिक हिँडाइ:</strong> 30 मिनेट हिँड्नुहोस् — सबैभन्दा सजिलो व्यायाम।</li><li><strong>चियामा चिनी कम:</strong> नेपाली चिया culture मा चिनी घटाउनुहोस्।</li><li><strong>डाक्टर परामर्श:</strong> BMI 30+ भए स्वास्थ्यकर्मीसँग सल्लाह लिनुहोस्।</li></ul>`,
      },
    ],
    howToSteps: [
      { title: 'वजन दर्ता', description: 'वजन kg मा दर्ता गर्नुहोस्।' },
      { title: 'उचाई दर्ता', description: 'उचाई cm वा feet/inches मा दर्ता गर्नुहोस्।' },
      { title: 'Calculate', description: 'एक click मा BMI तुरुन्त calculate हुन्छ।' },
      { title: 'श्रेणी हेर्नुहोस्', description: 'Normal, Overweight वा Obese कुन श्रेणीमा हुनुहुन्छ जान्नुहोस्।' },
      { title: 'सुझाव पढ्नुहोस्', description: 'BMI अनुसार स्वास्थ्य सुझाव पढ्नुहोस्।' },
    ],
    faqs: [
      { question: 'सामान्य BMI कति हुनुपर्छ?', answer: 'नेपाली/एसियाली मानिसका लागि 18.5–22.9 सामान्य हो। 23+ अधिक वजन र 25+ मोटोपन मानिन्छ।' },
      { question: 'BMI सूत्र के हो?', answer: 'BMI = वजन (kg) ÷ [उचाई (m)]²। उदाहरण: 60 kg, 1.60 m: BMI = 60 ÷ 2.56 = 23.4' },
      { question: 'नेपाली महिलाको आदर्श वजन कति?', answer: '5\'4" (163 cm) उचाईकी नेपाली महिलाको आदर्श वजन 47-59 kg हो।' },
      { question: 'उच्च BMI ले के रोग हुन्छ?', answer: 'BMI 30+ भएमा मधुमेह, उच्च रक्तचाप, मुटुको रोग र जोर्नी दुखाइको जोखिम बढ्छ।' },
      { question: 'BMI र स्वास्थ्य बीमामा के सम्बन्ध?', answer: 'नेपालका बीमा कम्पनीहरू health insurance लिँदा BMI जाँच गर्छन्। BMI 30+ भएमा premium बढी हुन सक्छ।' },
    ],
    relatedGuides: ['age-calculator-guide', 'emi-calculator-guide'],
    toolCTA: { heading: 'अहिले BMI Calculate गर्नुहोस्!', description: 'वजन र उचाई दर्ता गर्नुहोस् र तुरुन्त जान्नुहोस्।', buttonText: 'BMI Calculator खोल्नुहोस् →' },
  },

  // ── 3. IMAGE COMPRESSOR ────────────────────────────────────────
  {
    slug: 'image-compressor-guide',
    toolSlug: 'image-compressor',
    category: 'image-tools',
    title: 'फोटो कम्प्रेस गाइड: NTC/Ncell डेटा बचाउनुहोस् (2026)',
    subtitle: 'सरकारी आवेदन र WhatsApp/Viber का लागि फोटो compress — नेपाली सन्दर्भमा।',
    metaTitle: 'फोटो कम्प्रेसर - Image Size घटाउने सजिलो तरिका',
    metaDescription: 'फोटोको साइज घटाउनुहोस् गुणस्तर कायम राखेर। NTC/Ncell डेटा बचाउन, Lok Sewa-नागरिकता आवेदन र WhatsApp/Viber का लागि। निःशुल्क online image compressor।',
    targetKeyword: 'फोटो कम्प्रेस',
    secondaryKeywords: ['फोटो साइज घटाउने', 'NTC Ncell data bachau', 'Lok Sewa photo size', 'नागरिकता फोटो', 'image compress nepali', 'JPG PNG compress', 'passport photo nepal', 'online photo compressor free', 'mobile image compress', 'WhatsApp Viber photo'],
    lastUpdated: '2026-03-12',
    readingTime: '६ मिनेट पढ्ने',
    tags: ['फोटो', 'NTC', 'Lok Sewa', 'Data'],
    intro: `<p>नेपालमा NTC र Ncell को internet महँगो छ। <strong>फोटो कम्प्रेस</strong> गर्नाले डेटा बच्छ, Lok Sewa र नागरिकता जस्ता आवेदनमा upload सजिलो हुन्छ, र WhatsApp/Viber मा छिटो पठाउन सकिन्छ।</p><p>हाम्रो <strong>free image compressor</strong> ले JPG, PNG, WebP को size गुणस्तर कायम राखेर घटाउँछ।</p>`,
    sections: [
      {
        id: 'photo-compress-kina',
        title: 'फोटो Compress किन गर्ने?',
        content: `<ul><li><strong>NTC/Ncell डेटा बचत:</strong> 1 MB फोटोलाई 100 KB मा compress गर्दा 90% data बच्छ।</li><li><strong>Lok Sewa आवेदन:</strong> Portal मा 50 KB भन्दा कम फोटो चाहिन्छ।</li><li><strong>नागरिकता/पासपोर्ट:</strong> Online portal मा size limit हुन्छ।</li><li><strong>Mobile storage:</strong> Compressed फोटोले कम space लिन्छ।</li></ul>`,
      },
      {
        id: 'sarkari-photo-size',
        title: 'सरकारी आवेदनको फोटो Size Requirements',
        content: `<table><tr><th>आवेदन</th><th>Size</th><th>Format</th></tr><tr><td>Lok Sewa Aayog</td><td>&lt;50 KB</td><td>JPG</td></tr><tr><td>Passport</td><td>35×45 mm, &lt;100 KB</td><td>JPG</td></tr><tr><td>नागरिकता Online</td><td>&lt;200 KB</td><td>JPG/PNG</td></tr><tr><td>विश्वविद्यालय Admission</td><td>&lt;100 KB</td><td>JPG</td></tr><tr><td>Online Banking KYC</td><td>&lt;500 KB</td><td>JPG/PNG</td></tr></table>`,
      },
      {
        id: 'image-format',
        title: 'JPG vs PNG vs WebP: कुन राम्रो?',
        content: `<table><tr><th>Format</th><th>Best For</th><th>Transparency</th><th>Size</th></tr><tr><td>JPG</td><td>फोटो, social media</td><td>छैन</td><td>सानो</td></tr><tr><td>PNG</td><td>Logo, screenshot</td><td>छ</td><td>ठूलो</td></tr><tr><td>WebP</td><td>Website</td><td>छ</td><td>सबैभन्दा सानो</td></tr></table>`,
      },
    ],
    howToSteps: [
      { title: 'फोटो Upload', description: 'JPG, PNG वा WebP फोटो drag & drop वा Upload button बाट चुन्नुहोस्।' },
      { title: 'Compression Level', description: 'Light, Medium वा Strong compression छान्नुहोस्।' },
      { title: 'Compress', description: '"Compress" button थिच्नुहोस्।' },
      { title: 'तुलना', description: 'Original vs compressed size हेर्नुहोस्।' },
      { title: 'Download', description: 'Compressed फोटो download गर्नुहोस्।' },
    ],
    faqs: [
      { question: 'Lok Sewa को फोटो कति KB हुनुपर्छ?', answer: 'Lok Sewa Aayog को online portal मा फोटो 50 KB भन्दा कम हुनुपर्छ।' },
      { question: 'फोटो compress गर्दा गुणस्तर खराब हुन्छ?', answer: 'Medium compression (75-80%) मा आँखाले फरक थाहा नपाइने गरी size 60-70% घट्छ।' },
      { question: 'Mobile मा compress कसरी?', answer: 'Chrome browser मा toolsarena.in खोल्नुहोस्, फोटो upload गर्नुहोस् — कुनै app install गर्नु पर्दैन।' },
      { question: 'Passport फोटो size?', answer: 'नेपाली passport का लागि 35×45 mm, सेतो background, 100 KB भन्दा कम JPG चाहिन्छ।' },
      { question: 'एकैपटक धेरै फोटो compress?', answer: 'हो, हाम्रो tool ले एकैपटक multiple images compress गर्न सकिन्छ।' },
    ],
    relatedGuides: ['pdf-compressor-guide', 'qr-code-generator-guide'],
    toolCTA: { heading: 'अहिले फोटो Compress गर्नुहोस्!', description: 'Upload गर्नुहोस् र seconds मा size घटाउनुहोस्।', buttonText: 'Image Compressor खोल्नुहोस् →' },
  },

  // ── 4. QR CODE GENERATOR ──────────────────────────────────────
  {
    slug: 'qr-code-generator-guide',
    toolSlug: 'qr-code-generator',
    category: 'developer-tools',
    title: 'QR कोड बनाउने गाइड: FonePay, Khalti, eSewa (2026)',
    subtitle: 'नेपालमा digital payment QR code — FonePay, Khalti, eSewa र NepalQR standard।',
    metaTitle: 'QR कोड बनाउने - FonePay Khalti eSewa QR Free',
    metaDescription: 'निःशुल्क QR कोड बनाउनुहोस्। FonePay, Khalti, eSewa payment र व्यापारका लागि। NRB NepalQR मानदण्ड अनुसार। URL, WiFi, vCard सबको लागि अनलाइन QR generator।',
    targetKeyword: 'QR कोड बनाउने',
    secondaryKeywords: ['FonePay QR code', 'Khalti QR code', 'eSewa QR code', 'NepalQR standard', 'Nepal payment QR', 'NRB QR', 'व्यापारी QR', 'free QR nepal', 'WiFi QR nepali', 'QR code generator nepal'],
    lastUpdated: '2026-03-12',
    readingTime: '७ मिनेट पढ्ने',
    tags: ['QR Code', 'FonePay', 'Khalti', 'eSewa'],
    intro: `<p>नेपालमा digital payment को क्रान्ति आएको छ। <strong>QR कोड बनाउने</strong> tool ले तपाईं मिनेटमै आफ्नो QR code बनाउन सक्नुहुन्छ। FonePay, Khalti, eSewa र IMEPay प्रयोग गर्ने व्यापारीहरूका लागि QR code अनिवार्य भइसकेको छ।</p><p>NRB को NepalQR standard अनुसार एउटै QR code ले सबै digital payment apps बाट payment स्वीकार गर्छ — customer लाई कुनै charge लाग्दैन।</p>`,
    sections: [
      {
        id: 'qr-ke-ho',
        title: 'QR कोड के हो?',
        content: `<p>QR Code (Quick Response Code) एक 2D barcode हो। Smartphone camera ले scan गर्दा तुरुन्त information खुल्छ।</p><ul><li>Website URL</li><li>FonePay/Khalti/eSewa payment link</li><li>WiFi password</li><li>Contact details (vCard)</li><li>Text message</li></ul>`,
      },
      {
        id: 'nepal-payment-qr',
        title: 'नेपालमा Digital Payment QR (FonePay, Khalti, eSewa)',
        content: `<p>NRB ले NepalQR standard तोकेको छ — एउटा QR, सबै apps:</p><table><tr><th>Payment App</th><th>User Base</th></tr><tr><td>FonePay</td><td>सबैभन्दा ठूलो</td></tr><tr><td>eSewa</td><td>धेरै प्रयोगकर्ता</td></tr><tr><td>Khalti</td><td>बढ्दो</td></tr><tr><td>IMEPay</td><td>बैंक-linked</td></tr><tr><td>ConnectIPS</td><td>Bank direct</td></tr></table><p><strong>NRB नियम:</strong> Customer लाई कुनै transaction charge लाग्दैन।</p>`,
      },
      {
        id: 'qr-prakar',
        title: 'QR कोडका प्रकार र उपयोग',
        content: `<table><tr><th>QR प्रकार</th><th>उपयोग</th></tr><tr><td>URL QR</td><td>Website share</td></tr><tr><td>Payment QR</td><td>FonePay/eSewa payment</td></tr><tr><td>WiFi QR</td><td>Password share</td></tr><tr><td>vCard QR</td><td>Contact details</td></tr></table>`,
      },
      {
        id: 'qr-scan',
        title: 'QR कोड Scan कसरी गर्ने?',
        content: `<p><strong>Android:</strong> Camera app → QR code मा point गर्नुहोस्।</p><p><strong>iPhone:</strong> Default Camera app (iOS 11+)।</p><p><strong>FonePay/eSewa/Khalti:</strong> App → Scan QR → payment।</p>`,
      },
    ],
    howToSteps: [
      { title: 'QR Type छान्नुहोस्', description: 'URL, Payment, WiFi, vCard मध्ये छान्नुहोस्।' },
      { title: 'Information दर्ता', description: 'URL, payment ID वा WiFi password दर्ता गर्नुहोस्।' },
      { title: 'Generate', description: '"Generate QR" button थिच्नुहोस्।' },
      { title: 'Customize (optional)', description: 'रंग बदल्नुहोस् वा logo थप्नुहोस्।' },
      { title: 'Download/Share', description: 'PNG format मा download गर्नुहोस् वा print गर्नुहोस्।' },
    ],
    faqs: [
      { question: 'NepalQR standard के हो?', answer: 'NRB ले तोकेको national QR standard जसले सबै licensed payment apps (FonePay, eSewa, Khalti, IMEPay) लाई एउटै QR मा काम गर्न दिन्छ।' },
      { question: 'QR code निःशुल्क बनाउन सकिन्छ?', answer: 'हो, ToolsArena बाट बिल्कुल निःशुल्क। कुनै registration र expiry छैन।' },
      { question: 'FonePay QR कसरी बनाउने?', answer: 'FonePay merchant account बनाएर QR पाउन सकिन्छ। वा हाम्रो tool मा FonePay ID दर्ता गरेर QR बनाउन सकिन्छ।' },
      { question: 'QR code सधैँ valid रहन्छ?', answer: 'Static QR code सधैँका लागि valid रहन्छ। Dynamic QR मा expiry हुन सक्छ।' },
      { question: 'व्यापारीका लागि QR किन राम्रो?', answer: 'एउटा QR बाट FonePay, eSewa, Khalti सबैबाट payment आउँछ। Cash handle गर्नु पर्दैन, customer को कुनै charge लाग्दैन।' },
    ],
    relatedGuides: ['image-compressor-guide', 'pdf-compressor-guide'],
    toolCTA: { heading: 'अहिले QR Code बनाउनुहोस् — निःशुल्क!', description: 'Payment, WiFi, business card — जुनसुकै QR code अहिले बनाउनुहोस्।', buttonText: 'QR Code Generator खोल्नुहोस् →' },
  },

  // ── 5. AGE CALCULATOR ─────────────────────────────────────────
  {
    slug: 'age-calculator-guide',
    toolSlug: 'age-calculator',
    category: 'calculators',
    title: 'उमेर गणना गाइड: BS र AD उमेर (2026)',
    subtitle: 'बिक्रम संवत र ईश्वरी संवतमा सही उमेर — Lok Sewa, नागरिकता र SEE परीक्षाका लागि।',
    metaTitle: 'उमेर गणना - BS AD मा सही उमेर निकाल्नुहोस्',
    metaDescription: 'जन्म मिति बाट BS र AD दुवैमा सही उमेर गणना गर्नुहोस्। Lok Sewa Aayog, नागरिकता, SEE र सरकारी जागिरको उमेर सीमा जाँच्नुहोस्। निःशुल्क calculator।',
    targetKeyword: 'उमेर गणना',
    secondaryKeywords: ['उमेर गणना नेपाल', 'बिक्रम संवत उमेर', 'Lok Sewa उमेर सीमा', 'BS AD convert', 'नागरिकता उमेर', 'SEE उमेर', 'age calculator nepali BS', 'nepal age calculator', 'bikram sambat age', 'जन्म मिति उमेर'],
    lastUpdated: '2026-03-12',
    readingTime: '८ मिनेट पढ्ने',
    tags: ['उमेर', 'BS Calendar', 'Lok Sewa', 'नागरिकता'],
    intro: `<p><strong>उमेर गणना</strong> नेपालमा विशेष चुनौती हो किनकि हामी बिक्रम संवत (BS) प्रयोग गर्छौँ जुन AD भन्दा लगभग 56 वर्ष 8.5 महिना अघि छ। Lok Sewa Aayog, नागरिकता वा SEE परीक्षाका लागि सही उमेर जान्नु अत्यन्त जरुरी छ।</p><p>हाम्रो <strong>नेपाली age calculator</strong> ले BS र AD दुवैमा वर्ष, महिना, दिन — exact उमेर तुरुन्त बताउँछ।</p>`,
    sections: [
      {
        id: 'bs-ad-umera',
        title: 'BS र AD मा उमेर गणना',
        content: `<blockquote><strong>BS वर्ष = AD वर्ष + 56 वा 57</strong> (महिना अनुसार)</blockquote><table><tr><th>BS जन्म वर्ष</th><th>2083 BS मा उमेर</th><th>AD जन्म वर्ष</th></tr><tr><td>2040 BS</td><td>42-43</td><td>1983-84</td></tr><tr><td>2050 BS</td><td>32-33</td><td>1993-94</td></tr><tr><td>2055 BS</td><td>27-28</td><td>1998-99</td></tr><tr><td>2060 BS</td><td>22-23</td><td>2003-04</td></tr><tr><td>2065 BS</td><td>17-18</td><td>2008-09</td></tr></table>`,
      },
      {
        id: 'lok-sewa-age',
        title: 'Lok Sewa र सरकारी जागिरको उमेर सीमा',
        content: `<table><tr><th>पद</th><th>न्यूनतम</th><th>अधिकतम</th></tr><tr><td>Lok Sewa (General)</td><td>18 वर्ष</td><td>35 वर्ष</td></tr><tr><td>Gazetted Officer</td><td>21</td><td>35</td></tr><tr><td>Nepal Police</td><td>18</td><td>25</td></tr><tr><td>Nepal Army</td><td>17</td><td>21</td></tr><tr><td>Shiksha Sewa</td><td>21</td><td>40</td></tr><tr><td>नागरिकता</td><td>16</td><td>—</td></tr></table><p>उमेर गणना Lok Sewa advertisement published भएको मितिमा हुन्छ।</p>`,
      },
      {
        id: 'bs-months',
        title: 'बिक्रम संवतका महिनाहरू',
        content: `<p>BS का 12 महिना: <strong>वैशाख, जेठ, असार, श्रावण, भाद्र, आश्विन, कार्तिक, मंसिर, पुस, माघ, फाल्गुण, चैत</strong></p><p>वैशाख 1 गते BS नयाँ वर्ष सुरु हुन्छ (mid-April AD मा)।</p>`,
      },
    ],
    howToSteps: [
      { title: 'जन्म मिति दर्ता', description: 'BS वा AD मा जन्म मिति दर्ता गर्नुहोस्।' },
      { title: 'Calendar छान्नुहोस्', description: 'BS (बिक्रम संवत) वा AD छान्नुहोस्।' },
      { title: 'Calculate', description: 'वर्ष, महिना, दिन — exact उमेर तुरुन्त देखिन्छ।' },
      { title: 'Lok Sewa eligibility', description: 'उमेर सीमाको तुलना गर्नुहोस्।' },
      { title: 'Birthday countdown', description: 'अर्को जन्मदिन सम्म कति दिन बाँकी हेर्नुहोस्।' },
    ],
    faqs: [
      { question: 'BS र AD मा कति फरक छ?', answer: '2083 BS = 2026 AD। BS calendar AD भन्दा 56 वर्ष 8.5 महिना अघि छ।' },
      { question: 'नागरिकता बनाउन उमेर कति?', answer: '16 वर्ष पूरा भएपछि नागरिकता बनाउन सकिन्छ।' },
      { question: 'SEE परीक्षामा उमेर?', answer: 'SEE परीक्षाको लागि कुनै minimum age छैन। Class 10 पूरा गरेपछि दिन सकिन्छ — सामान्यतः 15-17 वर्षमा।' },
      { question: 'Lok Sewa को उमेर कहाँबाट calculate?', answer: 'Vacancy advertisement published भएको मितिमा उमेर calculate हुन्छ।' },
      { question: 'BS calendar का महिना नाम?', answer: 'वैशाख, जेठ, असार, श्रावण, भाद्र, आश्विन, कार्तिक, मंसिर, पुस, माघ, फाल्गुण, चैत।' },
    ],
    relatedGuides: ['bmi-calculator-guide', 'emi-calculator-guide'],
    toolCTA: { heading: 'अहिले उमेर Calculate गर्नुहोस्!', description: 'BS र AD दुवैमा exact उमेर जान्नुहोस्।', buttonText: 'उमेर गणना खोल्नुहोस् →' },
  },

  // ── 6. PERCENTAGE CALCULATOR ──────────────────────────────────
  {
    slug: 'percentage-calculator-guide',
    toolSlug: 'percentage-calculator',
    category: 'calculators',
    title: 'प्रतिशत गणना गाइड: SEE GPA र VAT 13% (2026)',
    subtitle: 'SEE GPA लाई percentage मा बदल्ने, VAT 13% र discount — नेपाली सन्दर्भ।',
    metaTitle: 'प्रतिशत गणना - SEE GPA VAT Discount Calculator',
    metaDescription: 'SEE GPA लाई percentage मा बदल्नुहोस्। नेपाल VAT 13%, discount, ब्याज र exam marks percentage। NEB grading system सहित निःशुल्क percentage calculator।',
    targetKeyword: 'प्रतिशत गणना',
    secondaryKeywords: ['SEE GPA percentage', 'VAT 13 Nepal', 'NEB percentage calculator', 'discount calculator nepali', 'ब्याज गणना', 'exam marks nepali', 'percentage formula nepali', 'CGPA percentage nepal', 'profit loss nepali', 'pratishat ganana'],
    lastUpdated: '2026-03-12',
    readingTime: '८ मिनेट पढ्ने',
    tags: ['SEE', 'GPA', 'VAT', 'Percentage'],
    intro: `<p><strong>प्रतिशत गणना</strong> दैनिक जीवनमा अत्यन्त काम लाग्छ। SEE GPA लाई percentage मा कसरी बदल्ने, नेपालमा VAT 13% कसरी calculate गर्ने — हाम्रो <strong>free calculator</strong> ले यी सबै तुरुन्त गर्छ।</p>`,
    sections: [
      {
        id: 'see-gpa-percentage',
        title: 'SEE परीक्षाको GPA लाई Percentage मा बदल्ने',
        content: `<blockquote><strong>Percentage = GPA × 25</strong> (NEB को official formula)</blockquote><p>उदाहरण: GPA 3.6 → 3.6 × 25 = <strong>90%</strong></p><table><tr><th>GPA</th><th>Grade</th><th>%</th></tr><tr><td>3.6–4.0</td><td>A+</td><td>90–100%</td></tr><tr><td>3.2–3.6</td><td>A</td><td>80–90%</td></tr><tr><td>2.8–3.2</td><td>B+</td><td>70–80%</td></tr><tr><td>2.4–2.8</td><td>B</td><td>60–70%</td></tr><tr><td>2.0–2.4</td><td>C+</td><td>50–60%</td></tr><tr><td>1.6–2.0</td><td>C</td><td>40–50%</td></tr></table>`,
      },
      {
        id: 'vat-nepal',
        title: 'नेपालमा VAT (13%) गणना',
        content: `<blockquote><strong>VAT सहित = Price × 1.13</strong></blockquote><p>उदाहरण: Rs. 1,000 मा 13% VAT = Rs. 1,130</p><p><strong>VAT निकाल्न:</strong> Rs. 1,130 ÷ 1.13 = Rs. 1,000</p><p>VAT मुक्त: कृषि उत्पादन, शिक्षा, स्वास्थ्य सेवा।</p>`,
      },
      {
        id: 'discount-byaj',
        title: 'Discount र ब्याज गणना',
        content: `<p><strong>Discount:</strong> Discounted Price = Original × (1 - Discount%/100)</p><p>उदाहरण: Rs. 2,000 मा 20%: Rs. 2,000 × 0.80 = Rs. 1,600</p><p><strong>Simple Interest:</strong> SI = (P × R × T) ÷ 100</p><p>उदाहरण: Rs. 50,000, 8%, 3 वर्ष: SI = Rs. 12,000</p>`,
      },
      {
        id: 'pratishat-formula',
        title: 'Percentage का Basic Formulas',
        content: `<table><tr><th>प्रश्न</th><th>सूत्र</th><th>उदाहरण</th></tr><tr><td>X को Y%?</td><td>(Y÷100)×X</td><td>500 को 13% = 65</td></tr><tr><td>X, Y को कति%?</td><td>(X÷Y)×100</td><td>45 of 150 = 30%</td></tr><tr><td>X मा Y% थप</td><td>X×(1+Y/100)</td><td>1000 मा 10% = 1100</td></tr></table>`,
      },
    ],
    howToSteps: [
      { title: 'Type छान्नुहोस्', description: 'Basic %, SEE GPA, VAT, Discount मध्ये छान्नुहोस्।' },
      { title: 'Values दर्ता', description: 'Number र percentage दर्ता गर्नुहोस्।' },
      { title: 'Calculate', description: 'एक click मा answer।' },
      { title: 'Step-by-step', description: 'Calculation कसरी भयो हेर्न सकिन्छ।' },
      { title: 'Multiple calculations', description: 'एकपछि अर्को calculations गर्न सकिन्छ।' },
    ],
    faqs: [
      { question: 'SEE GPA 3.2 भए percentage कति?', answer: '3.2 × 25 = 80% (Grade A, First Division)।' },
      { question: 'नेपालमा VAT कति?', answer: 'नेपालमा VAT 13% छ। सबै taxable goods र services मा लाग्छ।' },
      { question: '20% discount पछि Rs. 2,500?', answer: 'Rs. 2,500 × 0.80 = Rs. 2,000।' },
      { question: 'नेपाली बैंकको ब्याजदर?', answer: 'Savings मा 4-6%, Fixed Deposit मा 7-9%। NRB ले नियन्त्रण गर्छ।' },
      { question: 'Profit percentage?', answer: 'Profit% = [(SP-CP)÷CP]×100। CP=500, SP=600: 20% profit।' },
    ],
    relatedGuides: ['emi-calculator-guide', 'age-calculator-guide'],
    toolCTA: { heading: 'अहिले Percentage Calculate गर्नुहोस्!', description: 'SEE GPA, VAT, discount — seconds मा calculate गर्नुहोस्।', buttonText: 'Percentage Calculator खोल्नुहोस् →' },
  },

  // ── 7. PDF COMPRESSOR ─────────────────────────────────────────
  {
    slug: 'pdf-compressor-guide',
    toolSlug: 'pdf-compressor',
    category: 'pdf-tools',
    title: 'PDF साइज घटाउने गाइड: Lok Sewa आवेदन (2026)',
    subtitle: 'Lok Sewa, नागरिकता र विश्वविद्यालय आवेदनका लागि PDF size घटाउने सजिलो तरिका।',
    metaTitle: 'PDF साइज घटाउने - Lok Sewa PDF Compress Online',
    metaDescription: 'PDF फाइलको साइज अनलाइन घटाउनुहोस्। Lok Sewa Aayog, नागरिकता, पासपोर्ट र विश्वविद्यालय आवेदनको PDF size requirement पूरा गर्नुहोस्। निःशुल्क।',
    targetKeyword: 'PDF साइज घटाउने',
    secondaryKeywords: ['PDF compress nepal', 'Lok Sewa PDF size', 'PDF ghataune online', 'scan document compress', 'PDF compressor free nepal', 'नागरिकता PDF', 'TU admission PDF', 'online PDF tool nepal', 'mobile PDF compress', 'government portal PDF'],
    lastUpdated: '2026-03-12',
    readingTime: '६ मिनेट पढ्ने',
    tags: ['PDF', 'Lok Sewa', 'Document', 'आवेदन'],
    intro: `<p>Lok Sewa Aayog, नागरिकता र विश्वविद्यालयका online portal मा PDF upload गर्दा size limit हुन्छ। <strong>PDF साइज घटाउने</strong> tool ले कुनै पनि PDF को size मिनेटमा कम गर्न सकिन्छ — बिना software install गरे।</p>`,
    sections: [
      {
        id: 'pdf-kina',
        title: 'PDF साइज घटाउन किन आवश्यक?',
        content: `<ul><li><strong>Lok Sewa:</strong> Online portal मा document size limit कडा हुन्छ।</li><li><strong>नागरिकता/पासपोर्ट:</strong> Portal मा 200KB–1MB भन्दा बढी PDF reject हुन्छ।</li><li><strong>Email:</strong> Gmail मा 25 MB limit छ।</li><li><strong>Viber/WhatsApp:</strong> ठूलो PDF पठाउँदा धेरै data खर्च हुन्छ।</li></ul>`,
      },
      {
        id: 'lok-sewa-pdf',
        title: 'Lok Sewa र सरकारी Portal PDF Size Limits',
        content: `<table><tr><th>Portal</th><th>Maximum Size</th></tr><tr><td>Lok Sewa Online</td><td>200–500 KB</td></tr><tr><td>Passport</td><td>500 KB</td></tr><tr><td>नागरिकता Online</td><td>1 MB</td></tr><tr><td>TU/KU Admission</td><td>500 KB – 2 MB</td></tr><tr><td>Banking KYC</td><td>1–2 MB</td></tr></table>`,
      },
      {
        id: 'scan-compress',
        title: 'Scan गरिएको कागजात Compress',
        content: `<p>Mobile camera ले scan गरिएको PDF धेरै ठूलो हुन्छ (5-10 MB)।</p><ul><li>High compression मा 200-500 KB सम्म आउँछ</li><li>95% size reduction सम्भव</li><li>Adobe Scan वा CamScanner app ले scan गर्दा auto-compress हुन्छ</li></ul>`,
      },
    ],
    howToSteps: [
      { title: 'PDF Upload', description: 'PDF file drag & drop वा Upload button बाट चुन्नुहोस्।' },
      { title: 'Compression Level', description: 'Low, Medium वा High छान्नुहोस्।' },
      { title: 'Compress', description: '"Compress PDF" थिच्नुहोस्।' },
      { title: 'Size compare', description: 'Original vs compressed size हेर्नुहोस्।' },
      { title: 'Download', description: 'Compressed PDF download गर्नुहोस्।' },
    ],
    faqs: [
      { question: 'Lok Sewa PDF size कति?', answer: 'Lok Sewa portal मा 200-500 KB भन्दा कम PDF accept हुन्छ।' },
      { question: 'PDF compress गर्दा content हराउँछ?', answer: 'हुँदैन। Text र images optimize हुन्छ, content complete रहन्छ।' },
      { question: 'Scan गरिएको 10 MB compress हुन्छ?', answer: 'हो, High compression मा 10 MB को scan 300-500 KB सम्म compress हुन्छ।' },
      { question: 'Mobile मा कसरी?', answer: 'Chrome browser मा toolsarena.in खोल्नुहोस् — कुनै app install गर्नु पर्दैन।' },
      { question: 'Digital signature वाला PDF compress?', answer: 'सकिन्छ तर important legal documents का लागि Light compression प्रयोग गर्नुहोस्।' },
    ],
    relatedGuides: ['image-compressor-guide', 'qr-code-generator-guide'],
    toolCTA: { heading: 'अहिले PDF Compress गर्नुहोस्!', description: 'Upload गर्नुहोस्, seconds मा size घटाउनुहोस्।', buttonText: 'PDF Compressor खोल्नुहोस् →' },
  },

  // ── 8. JSON FORMATTER ─────────────────────────────────────────
  {
    slug: 'json-formatter-guide',
    toolSlug: 'json-formatter',
    category: 'developer-tools',
    title: 'JSON Formatter गाइड: नेपाली Developers (2026)',
    subtitle: 'JSON validate, format र debug — नेपाली IT professionals का लागि complete guide।',
    metaTitle: 'JSON फर्म्याटर - Developer Tool Nepal 2026',
    metaDescription: 'JSON code format, validate र beautify गर्नुहोस्। API response readable बनाउनुहोस्, errors find गर्नुहोस्। नेपाली developers का लागि निःशुल्क JSON formatter।',
    targetKeyword: 'JSON फर्म्याटर',
    secondaryKeywords: ['JSON format nepali', 'JSON validator nepal', 'API JSON formatter', 'JSON error fix', 'JSON beautify nepali', 'online JSON editor', 'JSON minify', 'JSON ke ho nepali', 'developer tools nepal', 'JSON to CSV nepal'],
    lastUpdated: '2026-03-12',
    readingTime: '६ मिनेट पढ्ने',
    tags: ['Developer', 'JSON', 'API', 'Nepal IT'],
    intro: `<p><strong>JSON Formatter</strong> developers को सबैभन्दा काम लाग्ने tool हो। नेपालमा IT sector तीव्र गतिले बढ्दैछ — eSewa, Khalti, FonePay, government digital services सबैमा JSON प्रयोग हुन्छ।</p><p>API बाट आएको messy JSON लाई readable format मा convert गर्नुहोस्, errors find गर्नुहोस्।</p>`,
    sections: [
      {
        id: 'json-ke-ho',
        title: 'JSON के हो?',
        content: `<p>JSON (JavaScript Object Notation) एक text format हो। Unformatted:<br/><code>{"name":"Ram","city":"Kathmandu"}</code></p><p>Formatted:<br/><code>{\n  "name": "Ram",\n  "city": "Kathmandu"\n}</code></p>`,
      },
      {
        id: 'json-errors',
        title: 'JSON मा सामान्य गल्ती र समाधान',
        content: `<table><tr><th>Error</th><th>कारण</th><th>समाधान</th></tr><tr><td>Unexpected token</td><td>Missing comma/bracket</td><td>Commas/brackets जाँच्नुहोस्</td></tr><tr><td>Property must be strings</td><td>Keys मा quotes छैन</td><td>"quotes" राख्नुहोस्</td></tr><tr><td>Trailing comma</td><td>Last element पछि comma</td><td>Comma हटाउनुहोस्</td></tr></table>`,
      },
      {
        id: 'json-uses',
        title: 'Nepal मा JSON को उपयोग',
        content: `<ul><li><strong>Fintech:</strong> eSewa, Khalti, FonePay API</li><li><strong>Government:</strong> nepal.gov.np APIs</li><li><strong>Mobile Apps:</strong> React Native, Flutter</li><li><strong>Open Data:</strong> data.nepalgovernment.gov.np</li></ul>`,
      },
    ],
    howToSteps: [
      { title: 'JSON paste', description: 'JSON code text box मा paste गर्नुहोस्।' },
      { title: 'Format/Validate', description: '"Format" वा "Validate" button थिच्नुहोस्।' },
      { title: 'Errors हेर्नुहोस्', description: 'Error भए exact line र कारण देखिन्छ।' },
      { title: 'Minify (optional)', description: 'Production का लागि JSON minify गर्नुहोस्।' },
      { title: 'Copy', description: 'Formatted JSON copy गर्नुहोस्।' },
    ],
    faqs: [
      { question: 'JSON formatter कसरी काम गर्छ?', answer: 'Messy JSON लाई proper indentation र line breaks थपेर readable format मा convert गर्छ।' },
      { question: 'Minified JSON के हो?', answer: 'Whitespace र newlines हटाएको JSON — file size कम र API faster।' },
      { question: 'JSON error कसरी थाहा पाउने?', answer: '"Validate" थिच्नुहोस् — error भए exact line number देखाउँछ।' },
      { question: 'CSV to JSON?', answer: 'हो, हाम्रो tool CSV to JSON conversion support गर्छ।' },
      { question: 'Nepal मा JSON कहाँ बढी use?', answer: 'eSewa, Khalti, FonePay, government digital services, mobile apps — सबैतिर।' },
    ],
    relatedGuides: ['word-counter-guide', 'pdf-compressor-guide'],
    toolCTA: { heading: 'अहिले JSON Format गर्नुहोस्!', description: 'Messy JSON readable बनाउनुहोस्।', buttonText: 'JSON Formatter खोल्नुहोस् →' },
  },

  // ── 9. EMI CALCULATOR ─────────────────────────────────────────
  {
    slug: 'emi-calculator-guide',
    toolSlug: 'emi-calculator',
    category: 'calculators',
    title: 'EMI क्याल्कुलेटर गाइड: नेपाली बैंक ऋण (2026)',
    subtitle: 'गृह ऋण, गाडी र व्यक्तिगत ऋणको EMI — नेपाली बैंकको दर र NRB नियम सहित।',
    metaTitle: 'EMI क्याल्कुलेटर - नेपाली बैंक ऋण किस्ता गणना',
    metaDescription: 'गृह ऋण, गाडी वा व्यक्तिगत ऋणको EMI तुरुन्त calculate गर्नुहोस्। नेपाली बैंकको 2026 ब्याजदर, NRB नियम र ऋण किस्ता तालिका सहित। निःशुल्क EMI calculator।',
    targetKeyword: 'EMI क्याल्कुलेटर',
    secondaryKeywords: ['Nepal bank loan EMI', 'griha rin EMI', 'ऋण किस्ता गणना', 'NRB home loan', 'Everest Bank EMI', 'loan calculator nepal', 'personal loan EMI nepal', 'EMI formula nepali', 'mortgage calculator nepal', 'home loan nepal 2026'],
    lastUpdated: '2026-03-12',
    readingTime: '१० मिनेट पढ्ने',
    tags: ['EMI', 'गृह ऋण', 'बैंक', 'Finance'],
    intro: `<p><strong>EMI क्याल्कुलेटर</strong> ले बताउँछ कि बैंकबाट ऋण लिएपछि हरेक महिना कति किस्ता तिर्नुपर्छ। नेपालमा घर किन्न, गाडी लिन वा व्यापार सुरु गर्न ऋण लिनु सामान्य भइसकेको छ।</p><p>NRB नियम अनुसार पहिलो पटक घर किन्नेले सम्पत्तिको 80% सम्म गृह ऋण पाउन सक्छन्।</p>`,
    sections: [
      {
        id: 'emi-ke-ho',
        title: 'EMI के हो?',
        content: `<p>EMI = Fixed Monthly Installment। हरेक EMI मा दुई भाग:</p><ul><li><strong>मूलधन (Principal):</strong> ऋण रकमको हिस्सा</li><li><strong>ब्याज (Interest):</strong> बैंकको कमाइ</li></ul><p>सुरुमा ब्याज बढी र मूलधन कम हुन्छ — यसलाई amortization भनिन्छ।</p>`,
      },
      {
        id: 'emi-formula',
        title: 'EMI गणनाको सूत्र',
        content: `<blockquote><strong>EMI = P × r × (1+r)ⁿ ÷ [(1+r)ⁿ − 1]</strong></blockquote><table><tr><th>ऋण</th><th>दर</th><th>अवधि</th><th>EMI</th><th>कुल ब्याज</th></tr><tr><td>Rs.25 लाख</td><td>10%</td><td>10 yr</td><td>Rs.33,038</td><td>Rs.14.6 लाख</td></tr><tr><td>Rs.25 लाख</td><td>10%</td><td>15 yr</td><td>Rs.26,853</td><td>Rs.23.3 लाख</td></tr><tr><td>Rs.25 लाख</td><td>10%</td><td>20 yr</td><td>Rs.24,126</td><td>Rs.33 लाख</td></tr></table>`,
      },
      {
        id: 'nepal-bank-rates',
        title: 'नेपाली बैंकहरूको गृह ऋण दर (2026)',
        content: `<table><tr><th>बैंक</th><th>ब्याजदर</th></tr><tr><td>Nepal Bank Limited</td><td>10% देखि</td></tr><tr><td>ADBL</td><td>10.25% देखि</td></tr><tr><td>Everest Bank</td><td>10.5% देखि</td></tr><tr><td>Global IME Bank</td><td>10.5% देखि</td></tr><tr><td>NMB Bank</td><td>10.75% देखि</td></tr><tr><td>Sunrise Bank</td><td>11% देखि</td></tr></table><p><strong>NRB नियम:</strong> First-time buyer लाई 80% LTV, maximum Rs. 3 crore।</p>`,
      },
      {
        id: 'talab-rin',
        title: 'तलव अनुसार ऋण eligibility',
        content: `<table><tr><th>मासिक तलव</th><th>Max EMI (40%)</th><th>Eligible ऋण</th></tr><tr><td>Rs.30,000</td><td>Rs.12,000</td><td>~Rs.12.4 लाख</td></tr><tr><td>Rs.50,000</td><td>Rs.20,000</td><td>~Rs.20.6 लाख</td></tr><tr><td>Rs.75,000</td><td>Rs.30,000</td><td>~Rs.31 लाख</td></tr></table>`,
      },
      {
        id: 'emi-ghatau',
        title: 'EMI घटाउने ५ तरिका',
        content: `<ol><li><strong>अवधि बढाउनुहोस्:</strong> 15 को सट्टा 20 वर्ष — EMI कम।</li><li><strong>Down payment बढाउनुहोस्:</strong> ऋण रकम घट्छ।</li><li><strong>कम दर भएको बैंक छान्नुहोस्।</strong></li><li><strong>Credit history राम्रो राख्नुहोस्।</strong></li><li><strong>Prepayment गर्नुहोस्:</strong> थप पैसा भएमा मूलधन घटाउनुहोस्।</li></ol>`,
      },
    ],
    howToSteps: [
      { title: 'ऋण रकम', description: 'कति ऋण लिने हो (Rs. मा) दर्ता गर्नुहोस्।' },
      { title: 'ब्याजदर', description: 'Annual interest rate % मा दर्ता गर्नुहोस्।' },
      { title: 'Tenure', description: 'कति वर्षमा ऋण चुक्ता गर्ने दर्ता गर्नुहोस्।' },
      { title: 'Calculate', description: 'Monthly EMI, total interest र total payment देखिन्छ।' },
      { title: 'Amortization', description: 'वर्षवर्षको breakdown हेर्नुहोस्।' },
    ],
    faqs: [
      { question: 'गृह ऋणको EMI कसरी calculate हुन्छ?', answer: 'EMI formula: P × r × (1+r)ⁿ ÷ [(1+r)ⁿ-1]। Rs.25 लाख, 10.5%, 20 yr: ~Rs.24,898/month।' },
      { question: 'नेपालमा गृह ऋणको ब्याज कति?', answer: '2026 मा 10-12% प्रतिवर्ष। NRB base rate अनुसार बैंकहरूको rate फरक हुन्छ।' },
      { question: 'NRB को नियम के छ?', answer: 'First-time buyer: 80% LTV, maximum Rs. 3 crore। EMI मासिक आयको 40% भन्दा बढी हुनु हुँदैन।' },
      { question: 'अवधि बढाए EMI घट्छ?', answer: 'हो, तर कुल ब्याज बढ्छ। 10 yr: Rs.33,038/m; 20 yr: Rs.24,126/m — तर कुल ब्याज दोब्बर।' },
      { question: 'गृह ऋणमा कर छुट?', answer: 'नेपालमा Income Tax Act अनुसार गृह ऋणको ब्याज र मूलधनमा कर छुट। CA सँग सल्लाह लिनुहोस्।' },
    ],
    relatedGuides: ['percentage-calculator-guide', 'age-calculator-guide'],
    toolCTA: { heading: 'अहिले EMI Calculate गर्नुहोस्!', description: 'गृह ऋण, गाडी वा व्यक्तिगत ऋण — exact EMI seconds मा।', buttonText: 'EMI Calculator खोल्नुहोस् →' },
  },

  // ── 10. UNIT CONVERTER ────────────────────────────────────────
  {
    slug: 'unit-converter-guide',
    toolSlug: 'unit-converter',
    category: 'converters',
    title: 'एकाइ रूपान्तरण: रोपनी, आना, धर्नी, टोल (2026)',
    subtitle: 'नेपालको परम्परागत नाप — रोपनी-आना (पहाड) र बिघा-कठ्ठा (तराई) को सम्पूर्ण guide।',
    metaTitle: 'एकाइ रूपान्तरण - रोपनी आना धर्नी टोल Convert',
    metaDescription: 'रोपनी, आना, धर्नी, टोल — नेपाली नापको रूपान्तरण। जग्गा किनबेच, सोना र अन्न नाप्न। पहाड र तराई दुवैका एकाइ convert गर्ने निःशुल्क tool।',
    targetKeyword: 'एकाइ रूपान्तरण',
    secondaryKeywords: ['रोपनी वर्गमिटर', '1 ropani square meter', 'धर्नी kg', 'टोल ग्राम gold', 'नेपाली जग्गा नाप', 'बिघा कठ्ठा तराई', 'ropani anna conversion', 'dharni kg nepali', 'tola gram nepal', 'unit converter nepali'],
    lastUpdated: '2026-03-12',
    readingTime: '९ मिनेट पढ्ने',
    tags: ['रोपनी', 'आना', 'धर्नी', 'जग्गा'],
    intro: `<p><strong>एकाइ रूपान्तरण</strong> नेपालमा जग्गा किनबेचमा, सोना किन्दा र दैनिक जीवनमा अत्यन्त काम लाग्छ। पहाडी जिल्लामा <strong>रोपनी-आना</strong> र तराईमा <strong>बिघा-कठ्ठा</strong> प्रयोग हुन्छ।</p><p><strong>1 टोल = 10 ग्राम</strong> (नेपालमा) — सोना किन्दा याद राख्नुहोस्।</p>`,
    sections: [
      {
        id: 'nepal-jagga',
        title: 'नेपालको जग्गा नाप्ने एकाइहरू',
        content: `<ul><li><strong>पहाडी प्रणाली:</strong> रोपनी, आना, पैसा, दाम — काठमाडौँ र पहाडी जिल्ला</li><li><strong>तराई प्रणाली:</strong> बिघा, कठ्ठा, धुर — मधेस र तराई</li></ul>`,
      },
      {
        id: 'ropani-table',
        title: '१ रोपनी = कति वर्गमिटर? (Complete Table)',
        content: `<table><tr><th>एकाइ</th><th>वर्गमिटर</th><th>वर्गफुट</th></tr><tr><td>1 रोपनी</td><td>508.72 m²</td><td>5,476 sq ft</td></tr><tr><td>1 आना</td><td>31.80 m²</td><td>342.25 sq ft</td></tr><tr><td>1 पैसा</td><td>7.95 m²</td><td>85.56 sq ft</td></tr><tr><td>1 दाम</td><td>1.99 m²</td><td>21.39 sq ft</td></tr></table><p><strong>तराई:</strong></p><table><tr><th>एकाइ</th><th>वर्गमिटर</th></tr><tr><td>1 बिघा</td><td>6,772.63 m²</td></tr><tr><td>1 कठ्ठा</td><td>338.63 m²</td></tr><tr><td>1 धुर</td><td>16.93 m²</td></tr></table>`,
      },
      {
        id: 'dharni-tola',
        title: 'धर्नी र टोल: नेपाली तौल एकाइ',
        content: `<table><tr><th>एकाइ</th><th>Grams</th><th>उपयोग</th></tr><tr><td>1 टोल</td><td>10 g</td><td>सोना, चाँदी</td></tr><tr><td>1 धर्नी</td><td>2,400 g (2.4 kg)</td><td>तरकारी, अन्न</td></tr><tr><td>1 पाउ</td><td>300 g</td><td>1 धर्नी = 8 पाउ</td></tr><tr><td>1 मान</td><td>600 g</td><td>दूध, तेल</td></tr><tr><td>1 पाथी</td><td>4,800 g</td><td>अन्न</td></tr></table><p><strong>नोट:</strong> नेपालमा 1 टोल = 10 ग्राम (भारतमा 11.66 ग्राम — फरक छ!)।</p>`,
      },
      {
        id: 'common-units',
        title: 'सामान्य एकाइ रूपान्तरण',
        content: `<table><tr><th>लम्बाइ</th><th>Convert</th></tr><tr><td>1 inch</td><td>2.54 cm</td></tr><tr><td>1 foot</td><td>30.48 cm</td></tr><tr><td>1 km</td><td>0.621 miles</td></tr></table><table><tr><th>तापक्रम</th><th>सूत्र</th></tr><tr><td>°C → °F</td><td>(°C×9/5)+32</td></tr><tr><td>°F → °C</td><td>(°F−32)×5/9</td></tr></table>`,
      },
    ],
    howToSteps: [
      { title: 'Category छान्नुहोस्', description: 'जग्गा, तौल, लम्बाइ, तापक्रम मध्ये छान्नुहोस्।' },
      { title: 'From Unit', description: 'Convert गर्ने unit छान्नुहोस् (रोपनी)।' },
      { title: 'To Unit', description: 'Convert गर्न चाहेको unit (वर्गमिटर)।' },
      { title: 'Value दर्ता', description: 'Convert गर्ने value दर्ता गर्नुहोस्।' },
      { title: 'Result', description: 'तुरुन्त converted value देखिन्छ।' },
    ],
    faqs: [
      { question: '1 रोपनी कति वर्गमिटर?', answer: '1 रोपनी = 508.72 वर्गमिटर = 5,476 वर्गफुट। 1 रोपनी = 16 आना।' },
      { question: 'रोपनी र बिघामा के फरक?', answer: 'रोपनी पहाडमा (508 m²) र बिघा तराईमा (6,773 m²) प्रयोग हुन्छ। बिघा रोपनीभन्दा 13x ठूलो।' },
      { question: '1 धर्नी कति kg?', answer: '1 धर्नी = 2.4 किलोग्राम = 8 पाउ।' },
      { question: 'नेपालमा टोल कति gram?', answer: 'नेपालमा 1 टोल = 10 ग्राम (भारतमा 11.664 ग्राम — फरक याद राख्नुहोस्)।' },
      { question: 'तराई र पहाडमा नाप किन फरक?', answer: 'ऐतिहासिक कारण — तराईमा Mughal/British India को बिघा system र पहाडमा नेवार/गुरुङ को रोपनी system। अहिले पनि दुवै क्षेत्रमा आफ्नै परम्परागत एकाइ प्रयोग हुन्छ।' },
    ],
    relatedGuides: ['percentage-calculator-guide', 'emi-calculator-guide'],
    toolCTA: { heading: 'अहिले Unit Convert गर्नुहोस्!', description: 'रोपनी, आना, धर्नी — कुनै पनि नेपाली एकाइ तुरुन्त convert।', buttonText: 'Unit Converter खोल्नुहोस् →' },
  },

];
