'use client';

import { useState, useCallback, useRef } from 'react';
import { FileDropzone } from '@/components/tools/FileDropzone';
import { downloadBlob } from '@/lib/utils';
import {
  FileSpreadsheet,
  Download,
  RotateCcw,
  Loader2,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react';

interface SheetData {
  name: string;
  headers: string[];
  rows: string[][];
}

interface ParsedFile {
  fileName: string;
  fileSize: number;
  sheets: SheetData[];
}

type PageOrientation = 'portrait' | 'landscape';

export function ExcelToPdfTool() {
  const [parsedFile, setParsedFile] = useState<ParsedFile | null>(null);
  const [activeSheet, setActiveSheet] = useState(0);
  const [loading, setLoading] = useState(false);
  const [converting, setConverting] = useState(false);
  const [error, setError] = useState('');
  const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
  const [pdfFilename, setPdfFilename] = useState('');
  const [orientation, setOrientation] = useState<PageOrientation>('portrait');
  const [fontSize, setFontSize] = useState(9);
  const previewRef = useRef<HTMLDivElement>(null);

  const parseFile = useCallback(async (files: File[]) => {
    const file = files[0];
    if (!file) return;

    setLoading(true);
    setError('');
    setParsedFile(null);
    setPdfBlob(null);
    setActiveSheet(0);

    try {
      const XLSX = await import('xlsx');
      const data = await file.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });

      const sheets: SheetData[] = workbook.SheetNames.map((name) => {
        const sheet = workbook.Sheets[name];
        const json: string[][] = XLSX.utils.sheet_to_json(sheet, {
          header: 1,
          defval: '',
          raw: false,
        });

        if (json.length === 0) {
          return { name, headers: [], rows: [] };
        }

        const headers = json[0].map((h) => String(h));
        const rows = json.slice(1).map((row) => row.map((cell) => String(cell)));

        return { name, headers, rows };
      });

      setParsedFile({
        fileName: file.name,
        fileSize: file.size,
        sheets,
      });
    } catch (e) {
      setError(
        `Failed to parse file: ${(e as Error).message}. Please ensure it is a valid .xlsx, .xls, or .csv file.`
      );
    } finally {
      setLoading(false);
    }
  }, []);

  const convertToPdf = useCallback(async () => {
    if (!parsedFile) return;

    setConverting(true);
    setError('');

    try {
      const { default: jsPDF } = await import('jspdf');
      // @ts-ignore - apply autotable plugin to jsPDF
      const { applyPlugin } = await import('jspdf-autotable');
      applyPlugin(jsPDF);

      const sheet = parsedFile.sheets[activeSheet];
      const isLandscape = orientation === 'landscape';
      const doc = new jsPDF({
        orientation: isLandscape ? 'landscape' : 'portrait',
        unit: 'pt',
        format: 'a4',
      });

      // Add title
      doc.setFontSize(14);
      doc.setTextColor(30, 30, 30);
      const title = `${parsedFile.fileName} — ${sheet.name}`;
      doc.text(title, 40, 35);

      // Add metadata line
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(
        `${sheet.rows.length} rows · ${sheet.headers.length} columns · Generated by ToolsArena`,
        40,
        48
      );

      // Build table data
      const tableHeaders = sheet.headers.length > 0 ? sheet.headers : [];
      const tableRows = sheet.rows;

      if (tableHeaders.length === 0 && tableRows.length === 0) {
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text('This sheet is empty.', 40, 80);
      } else {
        (doc as any).autoTable({
          head: tableHeaders.length > 0 ? [tableHeaders] : undefined,
          body: tableRows,
          startY: 58,
          margin: { left: 40, right: 40 },
          styles: {
            fontSize: fontSize,
            cellPadding: 4,
            overflow: 'linebreak',
            textColor: [30, 30, 30],
            lineColor: [200, 200, 200],
            lineWidth: 0.5,
          },
          headStyles: {
            fillColor: [59, 130, 246],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            fontSize: fontSize,
          },
          alternateRowStyles: {
            fillColor: [248, 250, 252],
          },
          didDrawPage: (data: { pageNumber: number }) => {
            // Footer on every page
            const pageHeight = doc.internal.pageSize.getHeight();
            doc.setFontSize(7);
            doc.setTextColor(160, 160, 160);
            doc.text(
              `Page ${data.pageNumber}`,
              doc.internal.pageSize.getWidth() / 2,
              pageHeight - 20,
              { align: 'center' }
            );
          },
        });
      }

      const blob = doc.output('blob');
      const filename = parsedFile.fileName.replace(/\.(xlsx|xls|csv)$/i, '') + '.pdf';
      setPdfBlob(blob);
      setPdfFilename(filename);
    } catch (e) {
      setError(`PDF conversion failed: ${(e as Error).message}`);
    } finally {
      setConverting(false);
    }
  }, [parsedFile, activeSheet, orientation, fontSize]);

  function reset() {
    setParsedFile(null);
    setPdfBlob(null);
    setPdfFilename('');
    setError('');
    setActiveSheet(0);
  }

  const currentSheet = parsedFile?.sheets[activeSheet];
  const totalRows = currentSheet ? currentSheet.rows.length : 0;
  const totalCols = currentSheet ? currentSheet.headers.length : 0;

  const selectClass =
    'w-full px-3 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm text-slate-700 dark:text-slate-300 focus:outline-none focus:ring-2 focus:ring-primary-500';

  return (
    <div className="space-y-5">
      {/* Settings */}
      <div className="grid sm:grid-cols-2 gap-4 p-4 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700">
        <div>
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
            Page Orientation
          </label>
          <select
            value={orientation}
            onChange={(e) => setOrientation(e.target.value as PageOrientation)}
            className={selectClass}
          >
            <option value="portrait">Portrait</option>
            <option value="landscape">Landscape (wide tables)</option>
          </select>
        </div>
        <div>
          <div className="flex justify-between mb-1.5">
            <label className="text-sm font-medium text-slate-700 dark:text-slate-300">
              Font Size
            </label>
            <span className="text-sm font-bold text-primary-700 dark:text-primary-400">
              {fontSize}pt
            </span>
          </div>
          <input
            type="range"
            min={6}
            max={14}
            step={1}
            value={fontSize}
            onChange={(e) => setFontSize(parseInt(e.target.value))}
            className="w-full h-2 bg-slate-200 dark:bg-slate-700 rounded-full appearance-none cursor-pointer accent-primary-800"
          />
          <div className="flex justify-between text-xs text-slate-400 mt-1">
            <span>6pt</span>
            <span>9pt (default)</span>
            <span>14pt</span>
          </div>
        </div>
      </div>

      {/* Format note */}
      <div className="flex items-start gap-2 p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl text-sm text-blue-700 dark:text-blue-300">
        <FileSpreadsheet className="w-4 h-4 shrink-0 mt-0.5" />
        <span>
          Supports <strong>.xlsx</strong>, <strong>.xls</strong>, and <strong>.csv</strong> files.
          Data is rendered as a clean table in PDF. Charts and conditional formatting are not
          preserved.
        </span>
      </div>

      {/* Upload area */}
      {!parsedFile && !loading && (
        <FileDropzone
          accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv"
          multiple={false}
          maxSizeMB={20}
          onFiles={parseFile}
          description=".xlsx, .xls, .csv files — max 20MB — 100% processed locally in your browser"
        />
      )}

      {/* Loading */}
      {loading && (
        <div className="flex flex-col items-center gap-3 py-12">
          <Loader2 className="w-10 h-10 text-primary-700 animate-spin" />
          <p className="text-sm text-slate-600 dark:text-slate-400">Parsing spreadsheet...</p>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl">
          <p className="text-sm text-red-700 dark:text-red-300">{error}</p>
          <button
            onClick={reset}
            className="mt-2 text-sm font-medium text-red-600 dark:text-red-400 hover:underline"
          >
            Try another file
          </button>
        </div>
      )}

      {/* Parsed file preview */}
      {parsedFile && !pdfBlob && !converting && (
        <div className="space-y-4">
          {/* File info */}
          <div className="grid grid-cols-3 gap-3 text-center">
            {[
              { label: 'Sheets', value: parsedFile.sheets.length },
              { label: 'Rows', value: totalRows.toLocaleString() },
              { label: 'Columns', value: totalCols },
            ].map((s) => (
              <div
                key={s.label}
                className="p-3 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700"
              >
                <p className="text-lg font-heading font-bold text-slate-900 dark:text-slate-100">
                  {s.value}
                </p>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{s.label}</p>
              </div>
            ))}
          </div>

          {/* Sheet tabs */}
          {parsedFile.sheets.length > 1 && (
            <div className="flex gap-1 bg-slate-100 dark:bg-slate-900 rounded-xl p-1 overflow-x-auto">
              {parsedFile.sheets.map((sheet, i) => (
                <button
                  key={sheet.name}
                  onClick={() => setActiveSheet(i)}
                  className={`flex-shrink-0 py-2 px-3 rounded-lg text-sm font-medium transition-all ${
                    activeSheet === i
                      ? 'bg-white dark:bg-slate-700 shadow text-primary-700 dark:text-primary-400'
                      : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300'
                  }`}
                >
                  {sheet.name}
                </button>
              ))}
            </div>
          )}

          {/* Table preview */}
          {currentSheet && (currentSheet.headers.length > 0 || currentSheet.rows.length > 0) && (
            <div ref={previewRef}>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
                  Preview — {currentSheet.name} ({totalRows} rows)
                </span>
                <div className="flex items-center gap-1 text-xs text-slate-400">
                  <ChevronLeft className="w-3 h-3" />
                  Scroll to see all columns
                  <ChevronRight className="w-3 h-3" />
                </div>
              </div>
              <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700 max-h-96 overflow-y-auto">
                <table className="min-w-full text-sm">
                  {currentSheet.headers.length > 0 && (
                    <thead className="bg-slate-50 dark:bg-slate-900 sticky top-0">
                      <tr>
                        <th className="px-3 py-2 text-left font-semibold text-slate-400 dark:text-slate-500 text-xs w-10">
                          #
                        </th>
                        {currentSheet.headers.map((h, i) => (
                          <th
                            key={i}
                            className="px-3 py-2 text-left font-semibold text-slate-600 dark:text-slate-400 whitespace-nowrap"
                          >
                            {h || `Col ${i + 1}`}
                          </th>
                        ))}
                      </tr>
                    </thead>
                  )}
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                    {currentSheet.rows.slice(0, 50).map((row, ri) => (
                      <tr
                        key={ri}
                        className="hover:bg-slate-50 dark:hover:bg-slate-700/50"
                      >
                        <td className="px-3 py-2 text-slate-400 dark:text-slate-500 text-xs">
                          {ri + 1}
                        </td>
                        {row.map((cell, ci) => (
                          <td
                            key={ci}
                            className="px-3 py-2 text-slate-700 dark:text-slate-300 whitespace-nowrap max-w-[200px] truncate"
                          >
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))}
                    {currentSheet.rows.length > 50 && (
                      <tr>
                        <td
                          colSpan={currentSheet.headers.length + 1}
                          className="px-3 py-3 text-center text-sm text-slate-400 dark:text-slate-500 italic"
                        >
                          Showing first 50 of {currentSheet.rows.length.toLocaleString()} rows. All
                          rows will be included in the PDF.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {currentSheet &&
            currentSheet.headers.length === 0 &&
            currentSheet.rows.length === 0 && (
              <div className="p-6 text-center bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700">
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  This sheet is empty.
                </p>
              </div>
            )}

          {/* Action buttons */}
          <div className="flex gap-3">
            <button
              onClick={convertToPdf}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-primary-800 hover:bg-primary-700 text-white font-medium rounded-xl transition-colors"
            >
              <FileSpreadsheet className="w-4 h-4" /> Convert to PDF
            </button>
            <button
              onClick={reset}
              className="flex items-center gap-2 px-4 py-3 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-medium rounded-xl transition-colors"
            >
              <RotateCcw className="w-4 h-4" /> Reset
            </button>
          </div>
        </div>
      )}

      {/* Converting */}
      {converting && (
        <div className="flex flex-col items-center gap-3 py-12">
          <Loader2 className="w-10 h-10 text-primary-700 animate-spin" />
          <p className="text-sm text-slate-600 dark:text-slate-400">Generating PDF...</p>
        </div>
      )}

      {/* PDF Result */}
      {pdfBlob && !converting && (
        <div className="space-y-4">
          <div className="flex items-center gap-3 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl">
            <CheckCircle className="w-6 h-6 text-green-600 dark:text-green-400 shrink-0" />
            <div className="flex-1 min-w-0">
              <p className="font-semibold text-green-800 dark:text-green-200">{pdfFilename}</p>
              <p className="text-sm text-green-600 dark:text-green-400 mt-0.5">
                {(pdfBlob.size / 1024).toFixed(0)} KB ·{' '}
                {parsedFile!.sheets[activeSheet].rows.length.toLocaleString()} rows ·{' '}
                {orientation} · {fontSize}pt font
              </p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => downloadBlob(pdfBlob, pdfFilename)}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-primary-800 hover:bg-primary-700 text-white font-medium rounded-xl transition-colors"
            >
              <Download className="w-4 h-4" /> Download PDF
            </button>
            <button
              onClick={() => {
                setPdfBlob(null);
                setPdfFilename('');
              }}
              className="flex items-center gap-2 px-4 py-3 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-medium rounded-xl transition-colors"
            >
              <RotateCcw className="w-4 h-4" /> Back to Preview
            </button>
          </div>

          <button
            onClick={reset}
            className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
          >
            <RotateCcw className="w-3.5 h-3.5" /> Convert another file
          </button>
        </div>
      )}
    </div>
  );
}
